In [105]:
import pandas as pd
from urllib.request import urlopen
import json

#EXTRACCIÓN DE LIBROS DEL AUTOR ADRIAN PAENZA CON EL API DE OPEN LIBRA (api pública)
url='https://www.etnassoft.com/api/v1/get/?book_author=Paenza&callback=?'
uclient=urlopen(url)
responsehtml=uclient.read()
uclient.close()
info=json.loads(responsehtml.decode()) #la respuesta se da en una lista de diccionarios, cada una para cada libro
df=pd.DataFrame(info) #creando un df para la info de todos los libros
print(list(df.columns)) #viendo las cabeceras de las columnas para filtrar solo algunas
df_paenza=df[['ID','title','content_short','publisher','publisher_date','pages','language']]
df_paenza

['ID', 'title', 'author', 'content', 'content_short', 'publisher', 'publisher_date', 'pages', 'language', 'url_details', 'url_download', 'cover', 'thumbnail', 'num_comments', 'categories', 'tags']

,ID,title,content_short,publisher,publisher_date,pages,language
0,10273,Matemática para Todos,"M&aacute;s juegos, problemas y enigmas en este...",Sudamericana,2012,349,spanish
1,1959,"¿Cómo, esto también es matemática?",&quot;La isla de los ojos celestes.&quot; &iqu...,Sudamericana,2011,311,spanish
2,1957,Matemática... ¿estás ahí? La vuelta al mundo e...,Ya lo extra&ntilde;&aacute;bamos. Y aqu&iacute...,Siglo XXI,2010,223,spanish
3,1955,Matemática... ¿estás ahí? Episodio 100,Bienvenidos al Episodio 100 de Matem&aacute;ti...,Siglo XXI,2008,256,spanish
4,1067,"Matemática… ¿Estás Ahí? Ep.3,14",Y se va la tercera&hellip; Entrar nuevamente e...,Siglo XXI Editores Argentina S.A.,2007,118,spanish
5,836,Matemática... ¿Estás ahí? Ep. 2,Matem&aacute;ticas&hellip; &iquest;est&aacute;...,Universidad Nacional de Quilmes,2006,235,spanish
6,776,Matemática... ¿Estás ahí?,"Hay libros que duran un d&iacute;a, y son buen...",Universidad Nacional de Quilmes,2005,119,spanish

In [125]:
url="https://www.etnassoft.com/api/v1/get/?id=776&callback=?"
uclient=urlopen(url)
responsehtml=uclient.read()
uclient.close()
info=json.loads(responsehtml.decode()) #la respuesta se da en una lista de diccionarios, cada una para cada libro
dic_libro=info[0]
# dic_libro
print(dic_libro["ID"])
print(dic_libro["title"])
print(dic_libro["author"])

776
Matemática... ¿Estás ahí?
Adrián Paenza